all: open multiple chain
	echo "All done and created"

chain:
	cd ChainingCollisionResolution && $(MAKE)

multiple:
	cd multiple_hashing && $(MAKE)

open:
	cd openadressing && $(MAKE)


clean_open :
	cd openadressing && make clean
clean_multiple:
	cd multiple_hashing && make clean
clean_chain:
	cd ChainingCollisionResolution && make clean