subsystems: subsystem_1 subsystem_2 subsystem_3
	echo "All done and created"

subsystem_1:
	cd ChainingCollisionResolution && $(MAKE)

subsystem_2:
	cd multiple_hashing && $(MAKE)

subsystem_3:
	cd openadressing && $(MAKE)
